name: Unit Tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  UnitTest:
    name: Python Unit Test
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@master
    with:
      python-version: '3.9'
